services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - SENTRY_DSN=https://examplePublicKey@o0.ingest.sentry.io/0
      - SENTRY_ENVIRONMENT=production
    volumes:
      - .:/app
      - ./finance.db:/app/finance.db
    depends_on:
      - prometheus
    command: ["uvicorn", "finance_tracker.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
